 name: Auto Commit

on:
  schedule:
    - cron: "*/40 * * * *"  # run every 40 minutes
  workflow_dispatch:        # allow manual run

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: git-check
        run: |
          git fetch
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit & Push changes
        if: env.changed == 'true'
        run: |
          git add .
          git commit -m "Auto commit: detected file changes"
          git push
